apiVersion: v1
kind: Service
metadata:
  name: edm-spring-boot-admin-app
  namespace: edm
  labels:
    spring-boot: "true"
    name: edm-spring-boot-admin-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    app: edm-spring-boot-admin-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edm-spring-boot-admin-app
  namespace: edm
  labels:
    app: edm-spring-boot-admin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edm-spring-boot-admin-app
  template:
    metadata:
      labels:
        app: edm-spring-boot-admin-app
    spec:
      containers:
        - name: edm-spring-boot-admin-app
          image: localhost:5000/edm-spring-boot-admin-app
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 30
            failureThreshold: 3

