kind: ConfigMap
apiVersion: v1
metadata:
  name: edm-spring-boot-admin-app
  namespace: edm
data:
  application.yml: |-
    spring:
      main:
        banner-mode: "off"
      cloud:
        kubernetes:
          discovery:
            all-namespaces: false
            service-labels:
              spring-boot: true

