kind: ConfigMap
apiVersion: v1
metadata:
  name: edm-spring-boot-admin-app
  namespace: edm
data:
  application.yml: |-
    spring:
     cloud:
      kubernetes:
        discovery:
          all-namespaces: false
          service-labels:
            spring-boot: true

