#!/bin/bash

set -x

export JAVA_HOME=$OPENSHIFT_DATA_DIR/jdk1.8.0_20
export PATH=$JAVA_HOME/bin:$PATH

cd $OPENSHIFT_REPO_DIR/.openshift

nohup java -Xms512m -Xmx512m -jar ../edm-webapp/target/*.jar --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} &

# just to see starting logs
sleep 120

