#!/bin/bash

cd $OPENSHIFT_REPO_DIR/.openshift

nohup java -Xms512m -Xmx512m -jar ../edm-webapp/target/*.jar --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} &

# just to see starting logs
sleep 120

