jdk:
  - openjdk11

services:
  - docker
  - xvfb

addons:
  chrome: stable
  apt:
    packages:
      - tesseract-ocr
      - tesseract-ocr-fra

before_install:
  - nvm install lts/dubnium
  - nvm use lts/dubnium
  - npm install -g @angular/cli

before_script:
  - cd docker/development_tools
  - docker-compose up -d elasticsearch
  - cd -

script:
  - ./scripts/run-build.sh
  - ./scripts/run-tests.sh

after_script:
  - cd docker/development_tools
  - docker-compose stop
  - docker-compose rm -f
  - cd -
