#!/bin/bash

echo "======================================================="
echo "mocked command : $0 $*"
echo "======================================================="
echo "Openshift comes with an old version of nodejs/npm"
echo "To simplify the build, you have to do it locally"
echo "You can help me on that point and submit pull request !"
echo "======================================================="

